# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

grant_1= Grant.new(title:"NIH Small Research Grant Program (Parent R03 Clinical Trial Not Allowed)", release_date:"11/5/2018", expired_date:"1/8/2020", document_number: "PA-19-052", document_type:"PA", activity_code:"RO3", clinical_trails:"Not_Allowed", url: "https://grants.nih.gov/grants/guide/pa-files/PA-19-052.html")
grant_1.description = GrantDescription.new(description: "National Institutes of Health (NIH)The NIH Small Research Grant Program supports small research projects that can be carried out in a short period of time with limited resources. This program supports different types of projects including pilot and feasibility studies; secondary analysis of existing data; small, self-contained research projects; development of research methodology; and development of new research technology. This Funding Opportunity Announcement does not accept applications proposing clinical trial(s).", term_vector: '["nih", "small", "research", "grant", "program", "parent", "r03", "clinical", "trial", "not", "allowed", "national", "institutes", "of", "health", "nih", "small", "research", "grant", "program", "supports", "research", "projects", "that", "can", "be", "carried", "out", "in", "short", "period", "of", "time", "limited", "this", "program", "supports", "different", "types", "of", "including", "pilot", "and", "feasibility", "secondary", "analysis", "of", "existing", "research", "development", "of", "research", "and", "development", "of", "new", "research", "funding", "opportunity", "announcement", "does", "not", "applications", "proposing", "clinical"]')
grant_1.save!

grant_2= Grant.new(title:"Research Project Grant (Parent R01 Clinical Trial Required)", release_date:"11/5/2018", expired_date:"1/8/2020", document_number: "PA-19-055", document_type:"PA", activity_code:"R01", clinical_trails:"Required", url: "https://grants.nih.gov/grants/guide/pa-files/PA-19-055.html")
grant_2.description = GrantDescription.new(description:"The NIH Research Project Grant supports a discrete, specified, circumscribed project in areas representing the specific interests and competencies of the investigator(s). This Parent Funding Opportunity Announcement requires that at least 1 clinical trial be proposed. The proposed project must be related to the programmatic interests of one or more of the participating NIH Institutes and Centers (ICs) based on their scientific missions. Applicants should note that some ICs (see Related Notices) only accept applications proposing mechanistic studies that meet NIH's definition of a clinical trial through this funding opportunity announcement.", term_vector: '["research", "project", "grant", "parent", "r01", "clinical", "trial", "required", "the", "nih", "research", "project", "grant", "supports", "circumscribed", "project", "in", "areas", "representing", "the", "specific", "and", "competencies", "of", "the", "this", "parent", "funding", "announcement", "requires", "that", "at", "least", "clinical", "trial", "be", "proposed", "project", "must", "be", "related", "to", "the", "programmatic", "interests", "of", "one", "or", "of", "the", "participating", "nih", "institutes", "and", "centers", "ics", "based", "on", "scientific", "should", "note", "that", "some", "ics", "see", "related", "notices", "only", "accept", "proposing", "mechanistic", "studies", "that", "meet", "definition", "of", "clinical", "through", "this", "funding", "opportunity"]')
grant_2.save!

